name: CD

on:
  push:
    branches:
      - 'testing-cd'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Executing remote command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        PASSWORD: ${{ secrets.PASSWORD }}
        debug: true
        script: |
          whoami
          ls -al