name: CD

on:
  push:
    branches:
      - 'master'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Executing remote command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        PASSWORD: ${{ secrets.PASSWORD }}
        script: |
          cd /var/www/raustin-portfolio
          git pull
          bundle install
          passenger stop -p 8080
          passenger start -a 127.0.0.1 -p 8080 -d -e production
          cd client
          npm install
          npm run build
          sudo service nginx restart